### ISSUE TITLE
proper define own colors - impossible to define "primary.dark"

### ISSUE THREAD

**Issue by sosite** [mikepenz/Materialize#10]
Recently I started used a dot for xml value names to divide nested names eg. `main_screen.header_btn.dark`.
Unfortunately, when i try to define `primary.dark` or `primary.light` then I received this error:
`variable primary_dark is already defined in class color`.

It's because during generate an `R` file compiler convert dots to underscore and it clashes with lib `colors.xml`:
```xml
<color name="primary_dark">@color/colorPrimaryDark</color>
<color name="primary_light">@color/colorPrimaryLight</color>
```

So... why even you chain it? And did I forced now to init my colors with:
```xml
<color name="colorPrimaryDark">#abc</color>
<color name="colorPrimaryLight">#def</color>
```

I use your other lib (MaterialDrawer) and I was suprised that I has any color clashes :open_mouth:.

I'll be grateful for your help.

**Comment by mikepenz** [comment]
@sosite I chain it because I renamed the colors in a prior version. And to not break all existing themes I chained them. 

I am not sure why it fails the R generation as it won't fail (or shouldn't) if you just define the color `primary_dark` in your `colors.xml`

**Comment by sosite** [comment]
When I use:
```xml
<color name="primary_dark">#abc</color>
<color name="primary_light">#def</color>
```
in place of
```xml
<color name="primary.dark">#abc</color>
<color name="primary.light">#def</color>
```
then all of course works. But just irritates me having an exception from my dot naming convention :wink:

**Comment by mikepenz** [comment]
@sosite I think this should be raised as general issue for the android build tools. As both should refer to the same entry. 

I expect that I can't really change anything regarding this
