### ISSUE TITLE
withStatusBarPadding() tints status bar a shade too dark?

### ISSUE THREAD

**Issue by drinfernoo** [mikepenz/Materialize#11]
When trying to use Materialize to setup my theme, I'm using this code:

`new MaterializeBuilder().withActivity(this).withStatusBarPadding(true).build();`

since I don't need a fullscreen activity, or a translucent status bar. However, this makes my status bar darker than intended.

My activity contains a Toolbar in the root layout, colored with my colorPrimary (md_green_500), but the status bar is much darker than colorPrimaryDark (md_green_700), and is closer to md_green_900. Why is this?

![device-2016-08-30-213948](https://cloud.githubusercontent.com/assets/2319508/18116184/6cc23ab8-6efa-11e6-8ea4-0e8107c79231.png)

**Comment by drinfernoo** [comment]
I should mention, the same coloring occurs without using withStatusBarPadding(true), but my Toolbar is drawn _behind_ the status bar, rather than _under_ it, which is what I'm trying to achieve.

**Comment by mikepenz** [comment]
What theme are you using? How exactly is your layout set up? Have you checked the sample app?

**Comment by drinfernoo** [comment]
For this activity, I haven't defined a specific theme. And yes, the implementation in the sample app (the code at least) is what gives me the result in the second screenshot.

**Comment by mikepenz** [comment]
How does your layout look like? 

The one in the sample app:
https://github.com/mikepenz/Materialize/blob/develop/app/src/main/res/layout/activity_simple.xml

The theme in the sample app:
https://github.com/mikepenz/Materialize/blob/develop/app/src/main/AndroidManifest.xml#L15

**Comment by drinfernoo** [comment]
After specifying a theme in my manifest, MaterialTheme.Light.DarkToolbar, and removing setStatusBarPadding(true), the status bar and Toolbar look the way they should. However, I can't seem to get my Toolbar to have white text instead of black.

I've also set this for my Toolbar layout:
`<android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="?attr/colorPrimary"
        android:elevation="4dp"
        android:minHeight="?attr/actionBarSize"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
        app:popupTheme="@style/ThemeOverlay.AppCompat.Light"/>`

**Comment by mikepenz** [comment]
The `toolbar` looks fine. It's exactly what I use for the sample apps too when they should have white text. 
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/res/layout/activity_sample_dark_toolbar.xml#L13

And I use the same theme for the main activity of the `MaterialDrawer` which has proper white text. :/

Anything else you set programatically?

**Comment by drinfernoo** [comment]
I wasn't able to get it working through the theme, but I finally got white text by setting this in code:

`mToolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(mToolbar);
        mToolbar.setTitleTextColor(getResources().getColor(R.color.md_white_1000));
        `

**Comment by mikepenz** [comment]
@drinfernoo ah ok :D 

The `Materialize` library can't set the theme on the `Toolbar` this is still necessary to be done on your own.
