### ISSUE TITLE
Wrong size returned by UIUtils.getNavigationBarHeight

### ISSUE THREAD

**Issue by Gounlaf** [mikepenz/Materialize#13]
Hi,

I got a problem with method `UIUtils.getNavigationBarHeight`, on a Samsung device (a SM-G920F ; it the ); actually, it's not really a bug due to Materialize, but by the manufacturer : the `@dimen/android:navigation_bar_height` is defined, but the navigation bar is a physical one.

I've found [here](https://stackoverflow.com/a/29938139/2098861) a solution, and it works (at least, for the specific device).

As attachment, a screenshot of the MaterialDrawer Sample app, on Fullscreen activity.

Should this "fix" be applied in method `UIUtils.getNavigationBarHeight`, or added in a separate method and called when necessary ?

Thanks for your time.

![device-2017-01-23-152421](https://cloud.githubusercontent.com/assets/236413/22207715/7872b1e6-e180-11e6-9669-5a8adba2df26.png)

**Comment by mikepenz** [comment]
I think it should be save to update the included method with the improved method found on SO

**Comment by Gounlaf** [comment]
I found another way [here](https://stackoverflow.com/questions/28983621/detect-soft-navigation-bar-availability-in-android-device-progmatically).

I'm doing some tests on physical devices (samsung, nexus), and emulator. I don't know yet what is the safest way.

I might be able to do a PR (at least, I will try).

**Comment by mikepenz** [comment]
@Gounlaf what did your tests result? do you want to do a PR?

**Comment by Gounlaf** [comment]
Hi @mikepenz,

I've not finished tests... It seems there is no way to handle it correctly on "all" devices.
Emulator has it's own behaviour. Physical devices from the same brand have different behaviours too.

So, no PR for the moment.

**Comment by mikepenz** [comment]
@Gounlaf ok thank you. The best would be anyway to let the system handle this. 

I think we can close this for now as we can't really do something against it, and it's a manufactures fault :D

**Comment by Gounlaf** [comment]
@mikepenz, Is it possible to provide a way to define or override the default calculation result (a static int/long that hold the value ?)
It will allow developers to "fix" the value if necessary, the way they want.

**Comment by mikepenz** [comment]
Might be possible yeah. but we should first look in how many areas this method is still used, and if it does not make more sense to remove it their, or if we have other solutions to solve this

**Comment by Gounlaf** [comment]
At least, you use it in MaterialDrawer (2 or 3 times) :)

**Comment by mikepenz** [comment]
As it seems to be an OEM issue, and there is no real alternative I think that's fine for most cases.
