### ISSUE TITLE
App content goes behind the NavBar

### ISSUE THREAD

**Issue by sliskiCode** [mikepenz/Materialize#15]
Hi there. I have problem with .withTranslucentNavigationBarProgrammatically(true) method. When I do the standard call of your library:
`new MaterializeBuilder().withActivity(this).withTranslucentNavigationBarProgrammatically(true).build();`
my screen content goes under the NavBar.
![device-2017-03-28-162318](https://cloud.githubusercontent.com/assets/1499459/24410305/0913718e-13d3-11e7-8de3-59d60d37063d.png)

My question is. Am I doing something wrong?

**Comment by mikepenz** [comment]
@sliskiCode that's the expected behaviour. if the NavigationBar is translucent, the content will go even below the NavigationBar. You can then either add padding / margin to you content. try to play around with the `fitsSystemWindows` flag.

**Comment by sliskiCode** [comment]
One more thing. When I use .withTintedNavigationBar(true) the behaviour is the same. That is also expected behaviour?

**Comment by mikepenz** [comment]
yeah as of this libraries implementation it is: https://github.com/mikepenz/Materialize/blob/develop/library/src/main/java/com/mikepenz/materialize/MaterializeBuilder.java#L226

You can disable the translucentNavigationBar if you set it to false after tinting the NavigationBar

**Comment by sliskiCode** [comment]
Awesome! Thanks Mike!

**Comment by sliskiCode** [comment]
Hmmm I did what you said and now it is ok but NavBar is not tinted :(
`new MaterializeBuilder()
                .withActivity(this)
                .withTintedNavigationBar(true)
                .withTranslucentNavigationBarProgrammatically(false)
                .build();`

**Comment by mikepenz** [comment]
@sliskiCode oh yeah stupid me. This is the result of the `mScrimInsetsLayout` not going below the `NavigationBar` in that case. 

Have you tryed to set `fitsSystemWindows=true` on your xml's root if you use the translucent NavigationBar? 


The thing is. Materialize was created to provide many material specific helpers for the different libs I have. Like the xml's, the themes, the ui helper classes. 
The core `MaterializeBuilder` was created for some specific usecases. Others work as a side fact (but maybe not perfect as this one it seems)

**Comment by sliskiCode** [comment]
I tried and it does not work. Ok then :( Thanks for your help

**Comment by mikepenz** [comment]
I am so sorry. So you just want to color the `NavigationBar` it seems?

**Comment by sliskiCode** [comment]
Yeah that is my goal:P

**Comment by mikepenz** [comment]
Have you tried to go the normal library free route  (Lollipop only) via the theme / window: http://stackoverflow.com/a/27839184/325479 ?

**Comment by sliskiCode** [comment]
Yeah I will go this route. Cheers

**Comment by mikepenz** [comment]
Awesome. :)

(Even if I create libs. If the system offers a feature, use it ;). Use the system. Don't fight it. :P)
