### ISSUE TITLE
How to make complete transparent Navigation Bar?

### ISSUE THREAD

**Issue by emreaktrk** [mikepenz/Materialize#16]
Hi Mike

Thanks for great library. I am just confused how to make complete transparent navigation bar? I am using MaterialTheme.Translucent and 

`       new MaterializeBuilder()
                .withActivity(this)
                .withFullscreen(true)
                .withTransparentStatusBar(true)
                .withTransparentNavigationBar(true)
                .build();`

Still semi transparent navigation bar on 7.1.2 on Emulator. 

Best regards
Emre

**Comment by mikepenz** [comment]
@emreaktrk which is the proper behaviour as what I needed from this library (which is the base for a few other of my libraries) 

You might just want to set the proper Fullscreen flags in your activity as of the android documentation.

**Comment by emreaktrk** [comment]
Thanks for response. I just needed to add WINDOW.FLAG_NO_LIMIT;

Cya
