### ISSUE TITLE
Contents in activities with actionbar as default overlapped by actionbar.

### ISSUE THREAD

**Issue by bskim45** [mikepenz/Materialize#4]
Hi, mike.
I manually implemented statusbar myself, and now Im trying to use this lib.

But I encountered with this:
Contents in activities with actionbar as default(such as AppCompatActivity) overlapped by actionbar.
Of course, views with toolbar are fine.

I already tried to set windowActionModeOverlay attribute to true, but it does not help.

Should I manually set root view paddings(attr/actionBarSize)?
I wonder if there's any methods provided by lib to solve this.

**Comment by mikepenz** [comment]
@bskim45 in activities with an ActionBar you should use an actionBar specific theme. And those are not supported by Materialize as those are more or less deprecated

**Comment by bskim45** [comment]
I see. Thanks :)
2015. 7. 27. 오전 3:53에 "Mike Penz" <notifications@github.com>님이 작성:
