### ISSUE TITLE
Base themes

### ISSUE THREAD

**Issue by alorma** [mikepenz/Materialize#6]
Hi @mikepenz 

I was looking for something that fits in this library i guess:

I want to use something like `pink_theme` with a feature like `?color/primary_400`, that will give me a `#EC407A` color

I think it's a good idea to have a base themes defined in the library, [`pink_theme`, `blue_grey_theme`, ...] that will provide the 50 ... A700 colors as attribute, so if i change the base theme of an activity it will change the colors automatically, and i don't have to change them.

What are your thoughts? Does it fit in Materialize? I will provide a PR

**Comment by mikepenz** [comment]
@alorma 

so there are already many base themes which are overwritten in special for different API versions, and usages. 
https://github.com/mikepenz/Materialize/blob/develop/library/src/main/res/values/styles.xml#L26

So the BaseBase theme is used as parent for the Base theme and then there come the different themes per API level, and specification (Translucent Toolbar, ActionBar, ...).

Those already define the `materialize` colors. As those do not fit your needs i recommend using one of the complete themes (not a base one) as parent for your theme. 

If you go and implement the color themes within materialize you will get a lot of combinations. Just for one color you would have to define themes for the following:
* MaterialTheme
* MaterialTheme.TranslucentStatus
* MaterialTheme.ActionBar
* MaterialTheme.ActionBar.TranslucentStatus
and all for with the light variants of the theme

So 8 themes for one color, if you now go on with all the colors you will get a lot of defined themes.

**Comment by alorma** [comment]
Yes, a lot of predefined themes.

It's just an idea, because at @gitstakrios i use a ot of variations of the same color (greys, blues, etc), and it's tedious to having it.

I thought about adding a declarable style with `md_color_###` so i can use them in my layouts, instead of changing colors, and either not need to create in my repository (as i use materialize sometimes in other repos).

But it's ok :D

**Comment by mikepenz** [comment]
as discussed via telegram
