### ISSUE TITLE
setStatusBarColor doesn't do anything

### ISSUE THREAD

**Issue by rubengees** [mikepenz/Materialize#8]
I want to change the color of the statusbar dynamically based on the content my App is currently showing. I use the `setStatusBarColor` method for that.  
I also use MaterialDrawer so I have a method like this:

```java
public void setStatusBarColor(@ColorInt int color){
    drawer.getMaterialize().setStatusBarColor(color);
}
```

But nothing happens. What am I doing wrong?

The MaterialDrawer is configured like the following:

```java
drawer = new DrawerBuilder(context)
                .withDrawerItems(generateDrawerItems())
                .withStickyDrawerItems(generateStickyDrawerItems())
                .withOnDrawerItemClickListener(onDrawerItemClickListener)
                .withShowDrawerOnFirstLaunch(true).withToolbar(toolbar)
                .withActionBarDrawerToggleAnimated(true).withHasStableIds(true)
                .withTranslucentStatusBar(true)
                .withSavedInstance(savedInstanceState).build();
```

**Comment by mikepenz** [comment]
@rubengees which version of the drawer?

**Comment by rubengees** [comment]
latest beta

**Comment by mikepenz** [comment]
@rubengees with the latest drawer the `StatusBarColor` is no longer managed via `Materialize` because I do not use the `ScrimInsetsFrameLayout` anymore https://github.com/mikepenz/Materialize/blob/develop/library/src/main/java/com/mikepenz/materialize/MaterializeBuilder.java#L326 so it won't hit the lines regarding the `StatusBarColor` 

You may change the statusbarcolor via:
```java
this.mActivity.getWindow().setStatusBarColor(Color);
```

But you are right, I should add this back

**Comment by rubengees** [comment]
I tried that approach already, it works but I loose the translucent action bar... (Drawer is below the status bar and not under it)  
I just tried it with the latest stable build of the Drawer, there the status bar remains translucent.

**Comment by mikepenz** [comment]
@rubengees oh yeah missed that one. Makes sense as the color will no longer be managed from the `DecorView` but from the `DrawerLayout` which is the first to consume the `fitsSystemWindows`. It may be a bit confusing, but that's the way Android and to be more specific the `fitsSystemWindows` work ;). 

To change the color you have to do this:

```java
result.getDrawerLayout().setStatusBarBackgroundColor(Color.RED);
```

**Comment by rubengees** [comment]
Hmm sadly not working. Same as before: No translucent status bar.  
I have

```java
public void setStatusBarColor(@ColorInt int color){
    drawer.getDrawerLayout().setStatusBarBackgroundColor(color);
}
```

**Comment by mikepenz** [comment]
@rubengees I just tried it. It only colored the `StatutsBar` and the drawer still overlaped the `StatusBar` :/ Perhaps instant run issue?

**Comment by rubengees** [comment]
Ah I'm sorry, it is working!
Had to rebuild, instant run is not very stable... :D

**Comment by rubengees** [comment]
Thank you once again for your quick help!

**Comment by mikepenz** [comment]
@rubengees haha I knew **instant run** was the issue :D

No problem. ;) My plesure
