### ISSUE TITLE
colors statusbar and navigationbar in kitkat

### ISSUE THREAD

**Issue by DJafari** [mikepenz/Materialize#9]
is'nt this library compatible with kitkat ?

**Comment by mikepenz** [comment]
@DJafari I removed support for coloring `StatusBar` pre `API 21` as this has a lot of bad side effects, and so I decided to shift the behavior a bit.

**Comment by farajist** [comment]
I just want to confirm something here : Does it mean that the `StatusBar` won't have a translucent state in pre `API 21`, right ?

**Comment by mikepenz** [comment]
@farajist exactly
